project_id = "howqpclucdljsovsjnrz"

[functions.braze-scheduler]
verify_jwt = false

[functions.braze-reconcile]
verify_jwt = false

[functions.braze-dedupe-fixtures]
verify_jwt = false

[functions.braze-webhook]
verify_jwt = false

[functions.fetch-braze-schedules]
verify_jwt = false

[functions.delete-braze-schedule]
verify_jwt = false

[functions.braze-cleanup-old-schedules]
verify_jwt = false

[functions.verify-braze-schedules]
verify_jwt = false

[functions.add-admin]
verify_jwt = false

[functions.braze-debug]
verify_jwt = false

[functions.gap-detection]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false
